### ISSUE TITLE
Documentos relativos ao projeto arquitetônico de todo campus piloto

### ISSUE THREAD

**Issue by marconiryan** [practice-uffs/tour-virtual#1]
Conseguir projeto arquitetônico do campus piloto

**Comment by minieradka** [comment]
link do projeto de LDS https://drive.google.com/drive/u/6/folders/1QqVUC72fvpfcbjjEEuWbNGY1HXc2b5Qr

**Comment by julia-zanini** [comment]
@luizatonial coloquei as identificações que meu amigo fez pra mim, mas ele ficou de me responder direito onde é o que na parte que ficou muito apertado.
Me diga se os nomes que eu coloquei nos prédios dá para ver ou se não ficou salvo

**Comment by minieradka** [comment]
como já conseguimos os projeto arquitetônico do campus irei deixar essa issue só no momento para a organização desses documentos [nesse link](https://drive.google.com/drive/u/6/folders/1QqVUC72fvpfcbjjEEuWbNGY1HXc2b5Qr) posteriormente iremos realocar os arquivos desse local
