### ISSUE TITLE
Reformular o texto base do Projeto Tour Virtual UFFS

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#10]
Será necessário atualizar a escrita base do projeto, adicionando as informações que já discutimos em reunião e organizando os próximos passos do projeto. 

[Cópia](https://drive.google.com/drive/u/6/folders/1MRAreIr07tEuLcBUGm6mANOW27Ja88kj)

**Comment by minieradka** [comment]
iniciei a revisão do documento e já listei os pontos que irei alterar, assim que finalizado será necessário uma revisão da equipe toda e posteriormente um revisão da escrita. https://docs.google.com/document/d/1kuyCo8FbEfMiLAanLcOmlxg1-ppubBwsnajzlhomaKU/edit?usp=share_link

**Comment by julia-zanini** [comment]
fiz várias alterações e revisão no texto do tour

**Comment by minieradka** [comment]
fiz mais algumas alterações peço que os demais membros também realizem uma revisão antes de decretar finalizado, @marconiryan  @luizatonial https://docs.google.com/document/d/1kuyCo8FbEfMiLAanLcOmlxg1-ppubBwsnajzlhomaKU/edit?usp=sharing
