### ISSUE TITLE
Wireframes da pagina 

### ISSUE THREAD

**Issue by marconiryan** [practice-uffs/tour-virtual#17]
Essa issue tem como objetivo criar o layout da página da tour virtual.

É necessário levar em consideração algumas coisas:
- Como será selecionado o campus.
- Quais informações devem aparecer ao clicar no mapa.
- Informações adicionais e legendas.
- Como faço para ir do mapa para as imagens 360.

**Comment by marconiryan** [comment]
@minieradka essa issue tem que ser feito pela equipe de design.

**Comment by minieradka** [comment]
vamos pensar como fazer esses pontos

**Comment by marconiryan** [comment]
O projeto vai seguir o layout do Google Maps usando:
### Controles: 
![image](https://user-images.githubusercontent.com/86175804/202757128-aece10db-8f69-4d8b-8247-91cf5f414f72.png)
### Barra de pesquisa
![image](https://user-images.githubusercontent.com/86175804/202757735-4ebd24a8-2aad-4c33-b11a-e6024d57081a.png)
### Explorar:
(Fotos tiradas pela comunidade acadêmica)
![image](https://user-images.githubusercontent.com/86175804/202758010-36808527-1301-4d17-8543-1b6937927193.png)
### Informação ao clicar num bloco:
![image](https://user-images.githubusercontent.com/86175804/202757461-c9d70f96-5e79-42f2-9d60-701f9b135632.png)

**Comment by minieradka** [comment]
maravilha obrigada ryan eu pesquisei uns modelos e to testando em breve novidades

**Comment by minieradka** [comment]
estou trabalhando nessa pagina do [figma](https://www.figma.com/file/nznirPtfynuDjwvr3wCNOF/Wireframe?node-id=0%3A1&t=YkMo70xmnCmhL3dh-1)

**Comment by marconiryan** [comment]
![image](https://user-images.githubusercontent.com/86175804/203466020-cb345532-dc64-4d64-a3e8-c481069b1e32.png)

**Comment by minieradka** [comment]
https://www.figma.com/file/nznirPtfynuDjwvr3wCNOF/Wireframe?node-id=0%3A1&t=roUbaMBIUEdhBLde-1 tenta de novo

**Comment by marconiryan** [comment]
Conversando com varias pessoas e com o Caimi, o layout do card não agradou muito. Refazer principalmente a parte do titulo e do texto. O titulo vazado não fica legal

**Comment by minieradka** [comment]
dei uma boa procurada não achei muitas referencias então me embasei no maps mesmo, fiz pequenas alterações talvez podemos alterar melhor posteriormente. Sobre o texto acho que não precisa ter muito espaçamento pra listar oq tem em cada bloco como aparece no link. coloquei um ícone que talvez possa ser usado pra levar para as imagens do marzipano.
https://www.figma.com/file/nznirPtfynuDjwvr3wCNOF/Wireframe?node-id=0%3A1&t=CBD4Z8Wp0DCkDFvM-1

**Comment by minieradka** [comment]
em reunião foi discutido a necessidade de alteração de algumas coisas irei dar continuidade na pagina inicial

**Comment by zorteaadriano** [comment]
Como ficou a versão final do protótipo no figma, ainda sem as alterações da logo da uffs:

![image](https://user-images.githubusercontent.com/74692811/221291624-6a7f11a0-90d5-4f54-91b1-c12c095db899.png)
