### ISSUE TITLE
Pesquisar outros projetos de mapas interativos baseados em SVG

### ISSUE THREAD

**Issue by marconiryan** [practice-uffs/tour-virtual#21]
A ideia é pesquisar outros projetos de mapas SVG para ter uma noção, ideia de como funciona.

**Comment by minieradka** [comment]
oq pensei que podemos usar dentro do figma é a isometria, dai o mapa pode ficar expandido por exemplo "imitando o 3d "  como nesse video aqui https://www.youtube.com/watch?v=hG8_Ytfqtps

**Comment by marconiryan** [comment]
É uma ideia que a gente pode testar, mas talvez seja mais dificil de implementar

**Comment by marconiryan** [comment]
[Documentação sobre SVGs interativos](https://www.petercollingridge.co.uk/tutorials/svg/interactive/)
[Mapas de todo o mundo em SVG](https://simplemaps.com/resources/svg-maps)
[Google Maps alternativo](https://www.openstreetmap.org/)
[Biblioteca Javascript para mapa](https://js.devexpress.com/Demos/WidgetsGallery/Demo/VectorMap/ColorsCustomization/AngularJS/Light/)
[Alguns projetos e plugins](https://codecanyon.net/search/map%20svg)
[Criar mapas interativos](https://maphub.net/explore)

**Comment by marconiryan** [comment]
Testar alguns itens dessa [Lista](https://www.hongkiat.com/blog/javascript-libraries-for-interactive-maps/).

**Comment by marconiryan** [comment]
Um [plugin](https://github.com/hueitan/snap.svg.zpd) para o Snap SVG que por acaso tem um [mapa interativo](https://hueitan.github.io/snap.svg.zpd/demo2.html)
