### ISSUE TITLE
Teste Inicial campus Laranjeiras do Sul 

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#25]
objetivo da issue é estruturar o teste inicial do campus após a coleta de dados

**Comment by minieradka** [comment]
Antes de iniciar o teste dentro do campus iremos coletar todas as informações necessarias para a construção dos mapas assim como iremos estruturar o projeto delimitando as fases e processos.

**Comment by julia-zanini** [comment]
estamos aguardando chegar o celular e o tripé de celular de Chapecó
