### ISSUE TITLE
Identificação Bloco dos professores LDS

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#26]
Identificar o que tem no bloco dos professores, bem como secretaria ou lugares importantes

**Comment by julia-zanini** [comment]
Está feito nessa pasta [aqui](https://drive.google.com/drive/folders/1QqVUC72fvpfcbjjEEuWbNGY1HXc2b5Qr), no documento [Identificação do Bloco](https://docs.google.com/document/d/1wrFjPizF20fRQc37Vg0jGyW9rrkDVG56XBHOMfEKZAM/edit), é só fazer o desenho da planta e colocar as marcações
