### ISSUE TITLE
identificação Setores/organizações LDS

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#27]
Identificar os setores e organizações importantes dentro do campus

**Comment by julia-zanini** [comment]
Acredito que essa issue já tenha sido feita através das outras (identificação do mapa do campus e identificação das salas dentro dos blocos do campus). acha que falta algum lugar?

**Comment by minieradka** [comment]
oi acredito que não, como vai ser bem detalhado, ainda precisamos de algumas informações além das que conhecemos como o SAE, Secretaria academica, etc seria importante apresentar tudo que tem dentro do campus
