### ISSUE TITLE
Identificação Áreas experimentais/ Laboratórios

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#28]
coletar informações importantes e necessárias sobre as áreas do campus

**Comment by julia-zanini** [comment]
Está feita nessa pasta [aqui](https://drive.google.com/drive/folders/1QqVUC72fvpfcbjjEEuWbNGY1HXc2b5Qr) de forma escrita, é necessário ainda fazer a planta e fazer as indicações
