### ISSUE TITLE
Legendas dos mapas

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#29]
essa issue tem por objetivo listar os principais elementos que devem conter em todos os mapas e plantas dos campis. Seja informações necessárias pro projeto. O  que é relevante em cada setor.

**Comment by marconiryan** [comment]
Poderia colocar essa informação no novo mapa

**Comment by marconiryan** [comment]
Falta identificar isso ai também
![image](https://user-images.githubusercontent.com/86175804/208575411-6607fced-a2fe-48b8-9681-730f7b0ac74a.png)

**Comment by minieradka** [comment]
criei um legenda de identificação dos elementos presentes no mapa, coloquei dentro do mapa mas tbm pode ficar em outro lugar  https://www.figma.com/file/EWgX5AP6ldkRn1WSN6uk9s/TOUR-VIRTUAL?node-id=184%3A2&t=qNhrU1gmZz8pOZos-1

**Comment by minieradka** [comment]
as legendas de cada mapas serão adicionadas nas respectivas pastas
