### ISSUE TITLE
Roteirizar principais pontos a serem registrados

### ISSUE THREAD

**Issue by marconiryan** [practice-uffs/tour-virtual#3]
Definir quais pontos são relevantes a serem registrados inicialmente no projeto

**Comment by minieradka** [comment]
> temos que testar qual a distância mais adequada entre um ponto e outro em ambientes externo e em ambientes internos.
> 
> @minieradka você teria disponibilidade de ir essa semana na uffs algum dia?

sim linda podemos combinar problema é a chuva né, podemos combinar quinta a tarde depois da reunião da equipe, partir de sexta estarei de atestado kk

**Comment by julia-zanini** [comment]
vamos quinta no ônibus das 15h40 então?

**Comment by julia-zanini** [comment]
acredito que os principais pontos a serem registrados já estão indicados nos próprios mapas (tanto nos de dentro dos blocos, que ainda precisam ser feitos, mas que já temos a [relação de salas](https://docs.google.com/document/d/1wrFjPizF20fRQc37Vg0jGyW9rrkDVG56XBHOMfEKZAM/edit), quanto no mapa geral do campus)

**Comment by minieradka** [comment]
criei um pequeno roteiro com algumas ressalvas que iremos organizar do projeto tbm https://docs.google.com/document/d/1GOjFsTybFOCWQU7b1pTXX-2D3_h8Gz4o/edit
