### ISSUE TITLE
Coleta de dados do campus LDS

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#30]
essa issue tem o objetivo de buscar e entrar em contato com a diretoria do campus e comunicação para coleta de dados sobre mapas, estruturas, setores, imagens áreas tudo que for relevante ao projeto

**Comment by minieradka** [comment]
entrei em contato com o campus iremos aguardar uma respostas, por enquanto consegui algumas informações a partir do site da universidade

**Comment by minieradka** [comment]
[nessa pasta](https://drive.google.com/drive/u/1/folders/1W-XRyBlODuHGhi8z3UZJ9giG9-W8SEjg) adicionei algumas informações que consegui no site assim como imagens que podem ajudar no projeto dos desenhos dos mapas @luizatonial @julia-zanini

**Comment by julia-zanini** [comment]
vou colocar as relações de salas dos professores do bloco docente, e algumas alterações dos três laboratórios

**Comment by minieradka** [comment]
conversei o diretor do campus que retornou que qualquer informação que precisarmos solicitar pro servidor Eloir, vou listar algumas coisa que são importantes e mandar email a ele

**Comment by minieradka** [comment]
foi coletado bastante informação no site da universidade e com base nas visitas, irei encerar essa issue pois ja finalizemos
