### ISSUE TITLE
Identificação dos demais blocos do campus LDS

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#31]
Sinalizar e identificar informações pertinentes sobre oq ocorre nos demais blocos do campus LDS

**Comment by julia-zanini** [comment]
michele, quais seriam os outros blocos que faltam? ou essa é uma issue anterior e agora você separou em issues diferentes (uma para o bloco A, outra para o bloco docente e outra para os laboratórios)?
