### ISSUE TITLE
Design dos mapas isométricos

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#33]
testar a viabilidade de criar mapas isométricos para o projeto tornando a estrutura mais atrativa e visualmente agradável.
Pensando que a identidade visual do projeto segue nessa linha de isometria 

Deve ser criado no figma: https://www.figma.com/file/EWgX5AP6ldkRn1WSN6uk9s/TOUR-VIRTUAL?node-id=0%3A1

exemplo do mapa: 
![image](https://user-images.githubusercontent.com/83479861/198416608-03fcdd3d-e66e-4807-85fa-014f47107c17.png)

**Comment by minieradka** [comment]
https://preview.codecanyon.net/item/availability-image-map-with-svg-map-builder/full_screen_preview/23362624?_ga=2.242037954.1136556591.1666914849-1039686154.1666914849

**Comment by marconiryan** [comment]
A ideia é legal mas é mais interessante fazer isso depois que a gente concluir todos os mapas.
