### ISSUE TITLE
Verificar utilização de planilhas para o backend

### ISSUE THREAD

**Issue by zorteaadriano** [practice-uffs/tour-virtual#36]
Nesse PR tem uma ideia dessa implementação:
https://github.com/practice-uffs/app-boas-vindas/pull/26

Ver: https://github.com/benborgers/opensheet

**Comment by marconiryan** [comment]
A Google fornece uma [API](https://github.com/google/google-api-javascript-client) para trabalhar com o docs, planilhas e etc. Acha viável trabalhar com ela ou usar o [OpenSheet](https://github.com/benborgers/opensheet)?

**Comment by marconiryan** [comment]
Testei com o [gspread](https://docs.gspread.org/en/v5.7.0/user-guide.html) e achei super facil trabalhar com ela. Esse [video](https://www.youtube.com/watch?v=bu5wXjz2KvU) explica melhor.
Basicamente tu configura uma conta do Google com a API e ela vai gerar um endereço de email. Na planilha tu coloca o endereço de email para ser compartilhado.
![image](https://user-images.githubusercontent.com/86175804/203701631-1fecd020-2cae-4045-a1b1-7d903d168764.png)

Você baixa o Json com a conta que você criou a API e importa no projeto. 
Em geral o código para ler uma célula é isso:

![image](https://user-images.githubusercontent.com/86175804/203701963-ba81e8fd-b8ba-452a-9549-08e914bcd94b.png)
