### ISSUE TITLE
Tirar fotos 360° da UFFS campos Chapecó 

### ISSUE THREAD

**Issue by gustavoSutil** [practice-uffs/tour-virtual#71]
Tirar as fotos 360° da UFFS campus Chapecó e criar um tour no marzipano com as mesmas.

**Comment by marconiryan** [comment]
@gustavoSutil quando criar uma issue, coloque apenas uma breve descrição. Mesmo que o titulo já explique o que tu vai fazer

**Comment by luizatonial** [comment]
issues que não são questões específicas do dev no projeto devem ser criadas no repositório programa

**Comment by luizatonial** [comment]
https://github.com/practice-uffs/programa/issues/1452
