### ISSUE TITLE
Mapa inicial campus LS

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#8]
Essa issue tem por objetivo organizar e testar com os matérias que já temos e criar os mapas e propostas discutidas do projeto.

Criei uma sessão exclusiva no [FIGMA](https://www.figma.com/file/EWgX5AP6ldkRn1WSN6uk9s/TOUR-VIRTUAL?node-id=1%3A855) para a edição. (necessário criar uma conta previamente) 

Temos uma formação especifica de criação de mapas feito no FIGMA utilizando imagens, vetores e formas. [link da formação](https://drive.google.com/file/d/1l8LwiThRnhxx-7lWh0_ycmwnXzmleqsg/view)

**Comment by lcaimi** [comment]
Coloquei as plantas (formato PDF) do campus LS na pasta de entrada do drive: https://drive.google.com/drive/folders/18eIJUqJTe070HDq-Y3rqswrGODdW9LaP?usp=sharing 
@luizatonial @marconiryan

**Comment by lcaimi** [comment]
> > atérias que já temos e criar os mapas e propostas discutidas do projeto.
> > Criei uma sessão exclusiva no [FIGMA](https://www.figma.com/file/EWgX5AP6ldkRn1WSN6uk9s/TOUR-VIRTUAL?node-id=1%3A855) para a edição. (necessário criar uma conta previamente)
> 
> Exemplo do mapa que buscamos: https://ufrj.br/a-ufrj/campi/

Acho que neste modelo visual usando a cor "oficial" (verde) da UFFS iria ficar ótimo.

**Comment by luizatonial** [comment]
> Coloquei as plantas (formato PDF) do campus LS na pasta de entrada do drive: https://drive.google.com/drive/folders/18eIJUqJTe070HDq-Y3rqswrGODdW9LaP?usp=sharing @luizatonial @marconiryan

coloquei nessa mesma pasta as imagens da implantação do campus em svg
