### ISSUE TITLE
Teste de equipamentos no campus LS/ CH

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/tour-virtual#9]
Essa issue tem por objetivo: testar ângulos e posicionamentos dos equipamentos fotográficos para que possamos iniciar os testes no campi escolhido. 

- [ ] definir o ângulo das câmeras (padrão para todas as imagens);
- [ ] Definir o mínimo de imagens que serão necessárias para edição final;
- [ ] Definir altura e plano das imagens;
- [ ] Distância entre cada elemento no cenário; 

Inicialmente os testes iniciaram no campi de Chapecó com @marconiryan e posteriormente depois de definido alguns elementos iniciaremos no campis de Laranjeiras do Sul.

**Comment by marconiryan** [comment]
Minha solução seria usar o [Street View](https://play.google.com/store/apps/details?id=com.google.android.street&hl=pt_BR&gl=US) pois já faz todo o trabalho e é bem fácil de usar. Basta seguir os pontos da tela. Único detalhe seria usar um tripé para celular para não gerar uma imagem tremida . 

Essa [demo](https://practice-uffs.github.io/tour-virtual-demo-1/) foi feita usando esse aplicativo  e sem tripé.

**Comment by minieradka** [comment]
são compreensivas suas colocações mesmo, teríamos um trabalho extenso pra definir um padrão e organizar essas imagens. O problema q vejo que provavelmente a qualidade da câmera do celular poderia afetar.

**Comment by marconiryan** [comment]
Acho que a qualidade não afeta tanto. O ideal seria fazer em um dia com bastante claridade. Mas tem umas fotos que eu fiz a noite e ficaram OK
