### ISSUE TITLE
Dropdown para agrupar as informações no tour

### ISSUE THREAD

**Issue by marconiryan** [practice-uffs/tour-virtual#91]
Foi decidido na issue [1451](https://github.com/practice-uffs/programa/issues/1451#issuecomment-1471902520) fazer um dropdown no panorama que agrega as informações, como:

![image](https://user-images.githubusercontent.com/86175804/225638623-bbe7f89d-1ded-4b5a-88d1-c52691210deb.png)

**Comment by marconiryan** [comment]
@luizatonial ficou mais ou menos assim. Alguma ideia para tirar duas vezes esse "interno"? Tem duas fotos internas, uma na entrada e uma no meio.

![image](https://user-images.githubusercontent.com/86175804/226512505-443ec5a0-93dc-43c5-b2ab-2607380b0b90.png)

**Comment by luizatonial** [comment]
tu acha muito ruim deixar acesso, na foto logo da entrada dos blocos? como tava na foto da descrição?

se não poderiamos colocar algo como "hall interno" na foto do meio

**Comment by marconiryan** [comment]
Como esta

Bloco A:
- Externo
- Interno
- Interno

### Ficaria
Bloco A:
- Acesso
- Interno
- Hall Interno
?
Todos os externos são fotos do acesso

**Comment by luizatonial** [comment]
podemos mandar no grupo também pra ver o que acham...

**Comment by marconiryan** [comment]
vou ver como que fica, qualquer coisa eu comento aqui sobre

**Comment by marconiryan** [comment]
@luizatonial dê uma [olhada](https://practice.uffs.edu.br/tour-virtual/ls/panorama)  de como ficou.
Se tiver algum problema no servidor, dê ctrl f5
